# netlify.toml

[dev]
  command = "npm start"
  port = 8888 

# production env
[context.production]
  command = "react-scripts build && mv build production"
  publish ="./production"

[context.production.environment]
  REACT_APP_BACKEND_URL = "https://namegen-backend-production.herokuapp.com"

# staging env
[context.staging]
  command = "react-scripts build && mv build staging"
  publish = "./staging"

[context.staging.environment]
  REACT_APP_BACKEND_URL = "https://namegen-backend-staging.herokuapp.com"

# redirect all subroutes to index.html
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

